stages:
  - code_quality
  - build
  - deploy
  - test

variables:
  DOCKER_DRIVER: overlay2
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/car_rental_db
  SPRING_DATASOURCE_USERNAME: car_rental
  SPRING_DATASOURCE_PASSWORD: carrental

before_script:
  - echo "Starting CI/CD Pipeline"

code_quality:
  stage: code_quality
  image: maven:3.8.4-openjdk-17
  script:
    - echo "Running mvn checkstyle for code quality..."
    - mvn checkstyle:check -Dcheckstyle.config.location=checkstyle.xml



build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building Docker image..."
    - docker build -t myrepo/carental:latest .
  only:
    - main

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Deploying Docker containers with docker-compose..."
    - docker-compose -f docker-compose.yml up -d
  only:
    - main


test:
  stage: test
  image: maven:3.8.4-openjdk-17
  services:
    - name: mysql:latest
      alias: mysql
  variables:
    MYSQL_DATABASE: 'car_rental_db'
    MYSQL_PASSWORD: 'carrental'
    MYSQL_ROOT_PASSWORD: 'root'
    MYSQL_USER: 'car_rental'
  before_script:
    - echo "Waiting for MySQL to be ready..."
    - apt-get update && apt-get install -y mysql-client
    - until mysql -hmysql -ucar_rental -pcarrental -e "show databases;" 2>/dev/null; do echo "Waiting..."; sleep 1; done
  script:
    - echo "MySQL is ready."
    - echo "Running mvn tests..."
    - mvn test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/
    reports:
      junit: target/surefire-reports/*.xml